name: p13helloworld_flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.0.1+1

  url_launcher: ^6.2.5

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#E9E5DD"
  image: assets/icons/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
